name: second-workflow
on: [push, pull_request]
jobs:
  run-linter-and-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          cache: 'pipenv'
      - run: pipenv install --dev
      - run: pipenv run pylint app
      - run: pipenv run nosetests
